name: sakellarios
favicon: null
layout_spectrum: 0.9635544552002102
typography_spectrum: 0.05852066120132804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5581469002645463
  lightness: 0.8351960424333811
  saturation: 0.5791889396496117
  rhythmicContrast: 0.5498446912970394
purpose: []
